"""Add priority field to issues table

Revision ID: 87801b5af600
Revises: 5d930f103385
Create Date: 2025-10-12 09:37:45.499836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87801b5af600'
down_revision: Union[str, None] = '5d930f103385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    issuepriority_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority')
    issuepriority_enum.create(op.get_bind(), checkfirst=True)

    # Add the column with a default value
    op.add_column('issues', sa.Column('priority', issuepriority_enum, nullable=False, server_default='MEDIUM'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'priority')
    # Drop the enum type
    sa.Enum(name='issuepriority').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
